import { Injectable } from '@angular/core';
import { BusinessType } from '../models/BusinessType';
import { BusinessCategory } from '../models/BusinessCategory';
import { State } from '../models/State';
import { City } from '../models/City';

const businessType: BusinessType[] = [
  { name: 'Sole Proprietorship' },
  { name: 'Partnership' },
  { name: 'Company' },
  { name: 'Public Sector' },
];

const states: State[] = [
  { id: 1, name: 'Wilayah Persekutuan' },
  { id: 2, name: 'Selangor' },
  { id: 3, name: 'Johor' },
  { id: 4, name: 'Kedah' },
  { id: 5, name: 'Kelantan' },
  { id: 6, name: 'Melaka' },
  { id: 7, name: 'Negeri Sembilan' },
  { id: 8, name: 'Pahang' },
  { id: 9, name: 'Penang' },
  { id: 10, name: 'Perak' },
  { id: 11, name: 'Perlis' },
  { id: 12, name: 'Sabah' },
  { id: 13, name: 'Sarawak' },
  { id: 14, name: 'Terengganu' },
];

const cities: City[] = [
  { id: 1, name: 'Ampang', stateId: 1 },
  { id: 2, name: 'Batu Caves', stateId: 1 },
  { id: 3, name: 'Cheras', stateId: 1 },
  { id: 4, name: 'Kuala Lumpur', stateId: 1 },
  { id: 5, name: 'Labuan', stateId: 1 },
  { id: 6, name: 'Putrajaya', stateId: 1 },
  { id: 7, name: 'Setapak', stateId: 1 },
  { id: 8, name: 'Ampang', stateId: 2 },
  { id: 9, name: 'Bandar Baru Bangi', stateId: 2 },
  { id: 10, name: 'Bandar Puncak Alam', stateId: 2 },
  { id: 11, name: 'Bangi', stateId: 2 },
  { id: 12, name: 'Banting', stateId: 2 },
  { id: 13, name: 'Batang Berjuntai', stateId: 2 },
  { id: 14, name: 'Batang Kali', stateId: 2 },
  { id: 15, name: 'Batu Arang', stateId: 2 },
  { id: 16, name: 'Batu Caves', stateId: 2 },
  { id: 17, name: 'Bukit Rotan', stateId: 2 },
  { id: 18, name: 'Cheras', stateId: 2 },
  { id: 19, name: 'Cyberjaya', stateId: 2 },
  { id: 20, name: 'Dengkil', stateId: 2 },
  { id: 21, name: 'Gombak', stateId: 2 },
  { id: 22, name: 'Hulu Langat', stateId: 2 },
  { id: 23, name: 'Jenjarom', stateId: 2 },
  { id: 24, name: 'Jeram', stateId: 2 },
  { id: 25, name: 'KLIA', stateId: 2 },
  { id: 26, name: 'Kajang', stateId: 2 },
  { id: 27, name: 'Kapar', stateId: 2 },
  { id: 28, name: 'Kerling', stateId: 2 },
  { id: 29, name: 'Klang', stateId: 2 },
  { id: 30, name: 'Kuala Kubu Baru', stateId: 2 },
  { id: 31, name: 'Kuala Selangor', stateId: 2 },
  { id: 32, name: 'Pandan', stateId: 2 },
  { id: 33, name: 'Pelabuhan Klang', stateId: 2 },
  { id: 34, name: 'Petaling Jaya', stateId: 2 },
  { id: 35, name: 'Puchong', stateId: 2 },
  { id: 36, name: 'Pulau Carey', stateId: 2 },
  { id: 37, name: 'Pulau Indah', stateId: 2 },
  { id: 38, name: 'Pulau Ketam', stateId: 2 },
  { id: 39, name: 'Rasa', stateId: 2 },
  { id: 40, name: 'Rawang', stateId: 2 },
  { id: 41, name: 'Sabak Bernam', stateId: 2 },
  { id: 42, name: 'Sekinchan', stateId: 2 },
  { id: 43, name: 'Semenyih', stateId: 2 },
  { id: 44, name: 'Sepang', stateId: 2 },
  { id: 45, name: 'Serdang', stateId: 2 },
  { id: 46, name: 'Serendah', stateId: 2 },
  { id: 47, name: 'Seri Kembangan', stateId: 2 },
  { id: 48, name: 'Shah Alam', stateId: 2 },
  { id: 49, name: 'Subang Airport', stateId: 2 },
  { id: 50, name: 'Subang Jaya', stateId: 2 },
  { id: 51, name: 'Sungai Ayer Tawar', stateId: 2 },
  { id: 52, name: 'Sungai Besar', stateId: 2 },
  { id: 53, name: 'Sungai Buloh', stateId: 2 },
  { id: 54, name: 'Sungai Pelek', stateId: 2 },
  { id: 55, name: 'Tanjong Karang', stateId: 2 },
  { id: 56, name: 'Tanjong Sepat', stateId: 2 },
  { id: 57, name: 'Telok Panglima Garang', stateId: 2 },
  { id: 58, name: 'Ayer Baloi', stateId: 3 },
  { id: 59, name: 'Ayer Hitam', stateId: 3 },
  { id: 60, name: 'Ayer Tawar', stateId: 3 },
  { id: 61, name: 'Bandar Penawar', stateId: 3 },
  { id: 62, name: 'Bandar Tenggara', stateId: 3 },
  { id: 63, name: 'Batu Anam', stateId: 3 },
  { id: 64, name: 'Batu Pahat', stateId: 3 },
  { id: 65, name: 'Bekok', stateId: 3 },
  { id: 66, name: 'Benut', stateId: 3 },
  { id: 67, name: 'Bukit Gambir', stateId: 3 },
  { id: 68, name: 'Bukit Pasir', stateId: 3 },
  { id: 69, name: 'Chaah', stateId: 3 },
  { id: 70, name: 'Endau', stateId: 3 },
  { id: 71, name: 'Gelang Patah', stateId: 3 },
  { id: 72, name: 'Gerisek', stateId: 3 },
  { id: 73, name: 'Gugusan Taib Andak', stateId: 3 },
  { id: 74, name: 'Jementah', stateId: 3 },
  { id: 75, name: 'Johor Bahru', stateId: 3 },
  { id: 76, name: 'Kahang', stateId: 3 },
  { id: 77, name: 'Kluang', stateId: 3 },
  { id: 78, name: 'Kota Tinggi', stateId: 3 },
  { id: 79, name: 'Kukup', stateId: 3 },
  { id: 80, name: 'Kulai', stateId: 3 },
  { id: 81, name: 'Labis', stateId: 3 },
  { id: 82, name: 'Layang-layang', stateId: 3 },
  { id: 83, name: 'Masai', stateId: 3 },
  { id: 84, name: 'Mersing', stateId: 3 },
  { id: 85, name: 'Muar', stateId: 3 },
  { id: 86, name: 'Nusajaya', stateId: 3 },
  { id: 87, name: 'Pagoh', stateId: 3 },
  { id: 88, name: 'Paloh', stateId: 3 },
  { id: 89, name: 'Panchor', stateId: 3 },
  { id: 80, name: 'Parit Jawa', stateId: 3 },
  { id: 23, name: 'Parit Raja', stateId: 3 },
  { id: 23, name: 'Parit Sulong', stateId: 3 },
  { id: 23, name: 'Pasir Gudang', stateId: 3 },
  { id: 23, name: 'Pekan Nenas', stateId: 3 },
  { id: 23, name: 'Pengerang', stateId: 3 },
  { id: 23, name: 'Pontian', stateId: 3 },
  { id: 23, name: 'Rengam', stateId: 3 },
  { id: 23, name: 'Rengit', stateId: 3 },
  { id: 23, name: 'Segamat', stateId: 3 },
  { id: 23, name: 'Semerah', stateId: 3 },
  { id: 23, name: 'Senai', stateId: 3 },
  { id: 23, name: 'Senggarang', stateId: 3 },
  { id: 23, name: 'Seri Gading', stateId: 3 },
  { id: 23, name: 'Seri Medan', stateId: 3 },
  { id: 23, name: 'Simpang Rengam', stateId: 3 },
  { id: 23, name: 'Sri Gading', stateId: 3 },
  { id: 23, name: 'Sri Medan', stateId: 3 },
  { id: 23, name: 'Sungai Mati', stateId: 3 },
  { id: 23, name: 'Tangkak', stateId: 3 },
  { id: 23, name: 'Ulu Tiram', stateId: 3 },
  { id: 23, name: 'Yong Peng', stateId: 3 },
  { id: 23, name: 'Alor Setar', stateId: 4 },
  { id: 23, name: 'Ayer Hitam', stateId: 4 },
  { id: 23, name: 'Baling', stateId: 4 },
  { id: 23, name: 'Bandar Baharu', stateId: 4 },
  { id: 23, name: 'Bedong', stateId: 4 },
  { id: 23, name: 'Bukit Kayu Hitam', stateId: 4 },
  { id: 23, name: 'Changloon', stateId: 4 },
  { id: 23, name: 'Gurun', stateId: 4 },
  { id: 23, name: 'Jeniang', stateId: 4 },
  { id: 23, name: 'Jitra', stateId: 4 },
  { id: 23, name: 'Karangan', stateId: 4 },
  { id: 23, name: 'Kepala Batas', stateId: 4 },
  { id: 23, name: 'Kodiang', stateId: 4 },
  { id: 23, name: 'Kota Kuala Muda', stateId: 4 },
  { id: 23, name: 'Kota Sarang Semut', stateId: 4 },
  { id: 23, name: 'Kuala Kedah', stateId: 4 },
  { id: 23, name: 'Kuala Ketil', stateId: 4 },
  { id: 23, name: 'Kuala Nerang', stateId: 4 },
  { id: 23, name: 'Kulim', stateId: 4 },
  { id: 23, name: 'Kupang', stateId: 4 },
  { id: 23, name: 'Langgar', stateId: 4 },
  { id: 23, name: 'Langkawi', stateId: 4 },
  { id: 23, name: 'Lunas', stateId: 4 },
  { id: 23, name: 'Merbok', stateId: 4 },
  { id: 23, name: 'Padang Serai', stateId: 4 },
  { id: 23, name: 'Pendang', stateId: 4 },
  { id: 23, name: 'Pokok Sena', stateId: 4 },
  { id: 23, name: 'Serdang', stateId: 4 },
  { id: 23, name: 'Sik', stateId: 4 },
  { id: 23, name: 'Simpang Empat', stateId: 4 },
  { id: 23, name: 'Sungai Petani', stateId: 4 },
  { id: 23, name: 'UUM', stateId: 4 },
  { id: 23, name: 'Yan', stateId: 4 },
  { id: 23, name: 'Ayer Lanas', stateId: 5 },
  { id: 23, name: 'Bachok', stateId: 5 },
  { id: 23, name: 'Cherang Ruku', stateId: 5 },
  { id: 23, name: 'Dabong', stateId: 5 },
  { id: 23, name: 'Gua Musang', stateId: 5 },
  { id: 23, name: 'Jeli', stateId: 5 },
  { id: 23, name: 'Kem Desa Pahlawan', stateId: 5 },
  { id: 23, name: 'Ketereh', stateId: 5 },
  { id: 23, name: 'Kota Bharu', stateId: 5 },
  { id: 23, name: 'Kuala Balah', stateId: 5 },
  { id: 23, name: 'Kuala Krai', stateId: 5 },
  { id: 23, name: 'Machang', stateId: 5 },
  { id: 23, name: 'Melor', stateId: 5 },
  { id: 23, name: 'Pasir Mas', stateId: 5 },
  { id: 23, name: 'Pasir Puteh', stateId: 5 },
  { id: 23, name: 'Pulai Chondong', stateId: 5 },
  { id: 23, name: 'Rantau Panjang', stateId: 5 },
  { id: 23, name: 'Selising', stateId: 5 },
  { id: 23, name: 'Tanah Merah', stateId: 5 },
  { id: 23, name: 'Temangan', stateId: 5 },
  { id: 23, name: 'Tumpat', stateId: 5 },
  { id: 23, name: 'Wakaf Bharu', stateId: 5 },
  { id: 23, name: 'Air Keroh', stateId: 6 },
  { id: 23, name: 'Alor Gajah', stateId: 6 },
  { id: 23, name: 'Asahan', stateId: 6 },
  { id: 23, name: 'Ayer Keroh', stateId: 6 },
  { id: 23, name: 'Bemban', stateId: 6 },
  { id: 23, name: 'Durian Tunggal', stateId: 6 },
  { id: 23, name: 'Jasin', stateId: 6 },
  { id: 23, name: 'Kem Trendak', stateId: 6 },
  { id: 23, name: 'Kuala Sungai Baru', stateId: 6 },
  { id: 23, name: 'Lubok China', stateId: 6 },
  { id: 23, name: 'Masjid Tanah', stateId: 6 },
  { id: 23, name: 'Melaka', stateId: 6 },
  { id: 23, name: 'Merlimau', stateId: 6 },
  { id: 23, name: 'Selandar', stateId: 6 },
  { id: 23, name: 'Sungai Rambai', stateId: 6 },
  { id: 23, name: 'Sungai Udang', stateId: 6 },
  { id: 23, name: 'Tanjong Kling', stateId: 6 },
  { id: 23, name: 'Bahau', stateId: 7 },
  { id: 23, name: 'Bandar Baru Enstek', stateId: 7 },
  { id: 23, name: 'Bandar Seri Jempol', stateId: 7 },
  { id: 23, name: 'Batu Kikir', stateId: 7 },
  { id: 23, name: 'Gemas', stateId: 7 },
  { id: 23, name: 'Gemencheh', stateId: 7 },
  { id: 23, name: 'Johol', stateId: 7 },
  { id: 23, name: 'Kota', stateId: 7 },
  { id: 23, name: 'Kuala Klawang', stateId: 7 },
  { id: 23, name: 'Kuala Pilah', stateId: 7 },
  { id: 23, name: 'Labu', stateId: 7 },
  { id: 23, name: 'Linggi', stateId: 7 },
  { id: 23, name: 'Mantin', stateId: 7 },
  { id: 23, name: 'Nilai', stateId: 7 },
  { id: 23, name: 'Port Dickson', stateId: 7 },
  { id: 23, name: 'Pusat Bandar Palong', stateId: 7 },
  { id: 23, name: 'Rantau', stateId: 7 },
  { id: 23, name: 'Rembau', stateId: 7 },
  { id: 23, name: 'Rompin', stateId: 7 },
  { id: 23, name: 'Seremban', stateId: 7 },
  { id: 23, name: 'Si Rusa', stateId: 7 },
  { id: 23, name: 'Simpang Durian', stateId: 7 },
  { id: 23, name: 'Simpang Pertang', stateId: 7 },
  { id: 23, name: 'Tampin', stateId: 7 },
  { id: 23, name: 'Tanjong Ipoh', stateId: 7 },
  { id: 23, name: 'Balok', stateId: 8 },
  { id: 23, name: 'Bandar Bera', stateId: 8 },
  { id: 23, name: 'Bandar Pusat Jengka', stateId: 8 },
  { id: 23, name: 'Bandar Tun Abdul Razak', stateId: 8 },
  { id: 23, name: 'Benta', stateId: 8 },
  { id: 23, name: 'Bentong', stateId: 8 },
  { id: 23, name: 'Brinchang', stateId: 8 },
  { id: 23, name: 'Bukit Fraser', stateId: 8 },
  { id: 23, name: 'Bukit Goh', stateId: 8 },
  { id: 23, name: 'Chenor', stateId: 8 },
  { id: 23, name: 'Chini', stateId: 8 },
  { id: 23, name: 'Damak', stateId: 8 },
  { id: 23, name: 'Dong', stateId: 8 },
  { id: 23, name: 'Gambang', stateId: 8 },
  { id: 23, name: 'Genting Highlands', stateId: 8 },
  { id: 23, name: 'Jaya Gading', stateId: 8 },
  { id: 23, name: 'Jerantut', stateId: 8 },
  { id: 23, name: 'Karak', stateId: 8 },
  { id: 23, name: 'Kemayan', stateId: 8 },
  { id: 23, name: 'Kuala Krau', stateId: 8 },
  { id: 23, name: 'Kuala Lipis', stateId: 8 },
  { id: 23, name: 'Kuala Rompin', stateId: 8 },
  { id: 23, name: 'Kuantan', stateId: 8 },
  { id: 23, name: 'Lanchang', stateId: 8 },
  { id: 23, name: 'Lurah Bilut', stateId: 8 },
  { id: 23, name: 'Maran', stateId: 8 },
  { id: 23, name: 'Mentakab', stateId: 8 },
  { id: 23, name: 'Muadzam Shah', stateId: 8 },
  { id: 23, name: 'Padang Tengku', stateId: 8 },
  { id: 23, name: 'Pekan', stateId: 8 },
  { id: 23, name: 'Raub', stateId: 8 },
  { id: 23, name: 'Ringlet', stateId: 8 },
  { id: 23, name: 'Sega', stateId: 8 },
  { id: 23, name: 'Sungai Koyan', stateId: 8 },
  { id: 23, name: 'Sungai Lembing', stateId: 8 },
  { id: 23, name: 'Sungai Ruan', stateId: 8 },
  { id: 23, name: 'Tanah Rata', stateId: 8 },
  { id: 23, name: 'Temerloh', stateId: 8 },
  { id: 23, name: 'Triang', stateId: 8 },
  { id: 23, name: 'Ayer Itam', stateId: 9 },
  { id: 23, name: 'Balik Pulau', stateId: 9 },
  { id: 23, name: 'Batu Ferringhi', stateId: 9 },
  { id: 23, name: 'Batu Maung', stateId: 9 },
  { id: 23, name: 'Bayan Lepas', stateId: 9 },
  { id: 23, name: 'Bukit Mertajam', stateId: 9 },
  { id: 23, name: 'Butterworth', stateId: 9 },
  { id: 23, name: 'Gelugor', stateId: 9 },
  { id: 23, name: 'Jelutong', stateId: 9 },
  { id: 23, name: 'Kepala Batas', stateId: 9 },
  { id: 23, name: 'Kubang Semang', stateId: 9 },
  { id: 23, name: 'Nibong Tebal', stateId: 9 },
  { id: 23, name: 'Padang Tembak', stateId: 9 },
  { id: 23, name: 'Penaga', stateId: 9 },
  { id: 23, name: 'Penang Hill', stateId: 9 },
  { id: 23, name: 'Perai', stateId: 9 },
  { id: 23, name: 'Permatang Pauh', stateId: 9 },
  { id: 23, name: 'Pulau Pinang', stateId: 9 },
  { id: 23, name: 'Simpang Ampat', stateId: 9 },
  { id: 23, name: 'Sungai Jawi', stateId: 9 },
  { id: 23, name: 'Tanjong Bungah', stateId: 9 },
  { id: 23, name: 'Tasek Gelugor', stateId: 9 },
  { id: 23, name: 'USM Pulau Pinang', stateId: 9 },
  { id: 23, name: 'Ayer Tawar', stateId: 10 },
  { id: 23, name: 'Bagan Datoh', stateId: 10 },
  { id: 23, name: 'Bagan Serai', stateId: 10 },
  { id: 23, name: 'Bandar Seri Iskandar', stateId: 10 },
  { id: 23, name: 'Batu Gajah', stateId: 10 },
  { id: 23, name: 'Batu Kurau', stateId: 10 },
  { id: 23, name: 'Behrang Stesen', stateId: 10 },
  { id: 23, name: 'Batu Gajah', stateId: 10 },
  { id: 23, name: 'Batu Kurau', stateId: 10 },
  { id: 23, name: 'Behrang Stesen', stateId: 10 },
  { id: 23, name: 'Bidor', stateId: 10 },
  { id: 23, name: 'Bota', stateId: 10 },
  { id: 23, name: 'Bruas', stateId: 10 },
  { id: 23, name: 'Changkat Jering', stateId: 10 },
  { id: 23, name: 'Changkat Keruing', stateId: 10 },
  { id: 23, name: 'Chenderong Balai', stateId: 10 },
  { id: 23, name: 'Chikus', stateId: 10 },
  { id: 23, name: 'Enggor', stateId: 10 },
  { id: 23, name: 'Gerik', stateId: 10 },
  { id: 23, name: 'Gopeng', stateId: 10 },
  { id: 23, name: 'Hutan Melintang', stateId: 10 },
  { id: 23, name: 'Intan', stateId: 10 },
  { id: 23, name: 'Ipoh', stateId: 10 },
  { id: 23, name: 'Jeram', stateId: 10 },
  { id: 23, name: 'Kampar', stateId: 10 },
  { id: 23, name: 'Kampung Gajah', stateId: 10 },
  { id: 23, name: 'Gampung Kepayang', stateId: 10 },
  { id: 23, name: 'Kamunting', stateId: 10 },
  { id: 23, name: 'Kuala Kangsar', stateId: 10 },
  { id: 23, name: 'Kuala Kurau', stateId: 10 },
  { id: 23, name: 'Kuala Sepatang', stateId: 10 },
  { id: 23, name: 'Langkap', stateId: 10 },
  { id: 23, name: 'Lenggong', stateId: 10 },
  { id: 23, name: 'Lumut', stateId: 10 },
  { id: 23, name: 'Malim Nawar', stateId: 10 },
  { id: 23, name: 'Mambang Di Awan', stateId: 10 },
  { id: 23, name: 'Manong', stateId: 10 },
  { id: 23, name: 'Matang', stateId: 10 },
  { id: 23, name: 'Padang Rengas', stateId: 10 },
  { id: 23, name: 'Pangkor', stateId: 10 },
  { id: 23, name: 'Pantai Remis', stateId: 10 },
  { id: 23, name: 'Parit', stateId: 10 },
  { id: 23, name: 'Parit Buntar', stateId: 10 },
  { id: 23, name: 'Pengkalan Hulu', stateId: 10 },
  { id: 23, name: 'Pusing', stateId: 10 },
  { id: 23, name: 'Rantau Panjang', stateId: 10 },
  { id: 23, name: 'Sauk', stateId: 10 },
  { id: 23, name: 'Selama', stateId: 10 },
  { id: 23, name: 'Seleoh', stateId: 10 },
  { id: 23, name: 'Seri Manjong', stateId: 10 },
  { id: 23, name: 'Simpang', stateId: 10 },
  { id: 23, name: 'Simpang Ampat Semanggol', stateId: 10 },
  { id: 23, name: 'Sitiawan', stateId: 10 },
  { id: 23, name: 'Slim River', stateId: 10 },
  { id: 23, name: 'Sungai Siput', stateId: 10 },
  { id: 23, name: 'Sungai Sumun', stateId: 10 },
  { id: 23, name: 'Sungkai', stateId: 10 },
  { id: 23, name: 'TLDM Lumut', stateId: 10 },
  { id: 23, name: 'Taiping', stateId: 10 },
  { id: 23, name: 'Tanjong Malim', stateId: 10 },
  { id: 23, name: 'Tanjong Piandang', stateId: 10 },
  { id: 23, name: 'Tanjong Rambutan', stateId: 10 },
  { id: 23, name: 'Tanjong Tualang', stateId: 10 },
  { id: 23, name: 'Tapah', stateId: 10 },
  { id: 23, name: 'Tapah Road', stateId: 10 },
  { id: 23, name: 'Teluk Intan', stateId: 10 },
  { id: 23, name: 'Temoh', stateId: 10 },
  { id: 23, name: 'Trolak', stateId: 10 },
  { id: 23, name: 'Trong', stateId: 10 },
  { id: 23, name: 'Tronoh', stateId: 10 },
  { id: 23, name: 'Ulu Bernam', stateId: 10 },
  { id: 23, name: 'Ulu Kinta', stateId: 10 },
  { id: 23, name: 'Arau', stateId: 11 },
  { id: 23, name: 'Kaki Bukit', stateId: 11 },
  { id: 23, name: 'Kangar', stateId: 11 },
  { id: 23, name: 'Kuala Perlis', stateId: 11 },
  { id: 23, name: 'Padang Besar', stateId: 11 },
  { id: 23, name: 'Simpang Ampat', stateId: 11 },
  { id: 23, name: 'Beaufort', stateId: 12 },
  { id: 23, name: 'Beluran', stateId: 12 },
  { id: 23, name: 'Beverly', stateId: 12 },
  { id: 23, name: 'Bongawan', stateId: 12 },
  { id: 23, name: 'Inaman', stateId: 12 },
  { id: 23, name: 'Keningau', stateId: 12 },
  { id: 23, name: 'Kota Belud', stateId: 12 },
  { id: 23, name: 'Kota Kinabalu', stateId: 12 },
  { id: 23, name: 'Kota Kinabatangan', stateId: 12 },
  { id: 23, name: 'Kota Marudu', stateId: 12 },
  { id: 23, name: 'Kuala Penyu', stateId: 12 },
  { id: 23, name: 'Kudat', stateId: 12 },
  { id: 23, name: 'Lahad Datu', stateId: 12 },
  { id: 23, name: 'Likas', stateId: 12 },
  { id: 23, name: 'Membakut', stateId: 12 },
  { id: 23, name: 'Menumbok', stateId: 12 },
  { id: 23, name: 'Nabawan', stateId: 12 },
  { id: 23, name: 'Pamol', stateId: 12 },
  { id: 23, name: 'Papar', stateId: 12 },
  { id: 23, name: 'Penampang', stateId: 12 },
  { id: 23, name: 'Putatan', stateId: 12 },
  { id: 23, name: 'Sandakan', stateId: 12 },
  { id: 23, name: 'Semporna', stateId: 12 },
  { id: 23, name: 'Sipitang', stateId: 12 },
  { id: 23, name: 'Tambunan', stateId: 12 },
  { id: 23, name: 'Tamparuli', stateId: 12 },
  { id: 23, name: 'Tanjung Aru', stateId: 12 },
  { id: 23, name: 'Tawau', stateId: 12 },
  { id: 23, name: 'Tenghilan', stateId: 12 },
  { id: 23, name: 'Tenom', stateId: 12 },
  { id: 23, name: 'Tuaran', stateId: 12 },
  { id: 23, name: 'Asajaya', stateId: 13 },
  { id: 23, name: 'Balingian', stateId: 13 },
  { id: 23, name: 'Baram', stateId: 13 },
  { id: 23, name: 'Bau', stateId: 13 },
  { id: 23, name: 'Bekenu', stateId: 13 },
  { id: 23, name: 'Belaga', stateId: 13 },
  { id: 23, name: 'Belawai', stateId: 13 },
  { id: 23, name: 'Betong', stateId: 13 },
  { id: 23, name: 'Bintangor', stateId: 13 },
  { id: 23, name: 'Bintulu', stateId: 13 },
  { id: 23, name: 'Dalat', stateId: 13 },
  { id: 23, name: 'Daro', stateId: 13 },
  { id: 23, name: 'Debak', stateId: 13 },
  { id: 23, name: 'Engkilili', stateId: 13 },
  { id: 23, name: 'Julau', stateId: 13 },
  { id: 23, name: 'Kabong', stateId: 13 },
  { id: 23, name: 'Kanowit', stateId: 13 },
  { id: 23, name: 'Kapit', stateId: 13 },
  { id: 23, name: 'Kota Samarahan', stateId: 13 },
  { id: 23, name: 'Kuching', stateId: 13 },
  { id: 23, name: 'Lawas', stateId: 13 },
  { id: 23, name: 'Limbang', stateId: 13 },
  { id: 23, name: 'Lingga', stateId: 13 },
  { id: 23, name: 'Long Lama', stateId: 13 },
  { id: 23, name: 'Lubok Antu', stateId: 13 },
  { id: 23, name: 'Lundu', stateId: 13 },
  { id: 23, name: 'Lutong', stateId: 13 },
  { id: 23, name: 'Matu', stateId: 13 },
  { id: 23, name: 'Miri', stateId: 13 },
  { id: 23, name: 'Mukah', stateId: 13 },
  { id: 23, name: 'Nanga Medamit', stateId: 13 },
  { id: 23, name: 'Niah', stateId: 13 },
  { id: 23, name: 'Pusa', stateId: 13 },
  { id: 23, name: 'Roban', stateId: 13 },
  { id: 23, name: 'Saratok', stateId: 13 },
  { id: 23, name: 'Sarikei', stateId: 13 },
  { id: 23, name: 'Sebauh', stateId: 13 },
  { id: 23, name: 'Sebuyau', stateId: 13 },
  { id: 23, name: 'Sibu', stateId: 13 },
  { id: 23, name: 'Siburan', stateId: 13 },
  { id: 23, name: 'Simunjan', stateId: 13 },
  { id: 23, name: 'Song', stateId: 13 },
  { id: 23, name: 'Spaoh', stateId: 13 },
  { id: 23, name: 'Sri Aman', stateId: 13 },
  { id: 23, name: 'Sundar', stateId: 13 },
  { id: 23, name: 'Tatau', stateId: 13 },
  { id: 23, name: 'Ajil', stateId: 14 },
  { id: 23, name: 'Al Muktafi Billah Shah', stateId: 14 },
  { id: 23, name: 'Ayer Puteh', stateId: 14 },
  { id: 23, name: 'Bukit Besi', stateId: 14 },
  { id: 23, name: 'Bukit Payong', stateId: 14 },
  { id: 23, name: 'Ceneh', stateId: 14 },
  { id: 23, name: 'Chalok', stateId: 14 },
  { id: 23, name: 'Cukai', stateId: 14 },
  { id: 23, name: 'Dungun', stateId: 14 },
  { id: 23, name: 'Jerteh', stateId: 14 },
  { id: 23, name: 'Kampung Raja', stateId: 14 },
  { id: 23, name: 'Kemasek', stateId: 14 },
  { id: 23, name: 'Kerteh', stateId: 14 },
  { id: 23, name: 'Ketengah Jaya', stateId: 14 },
  { id: 23, name: 'Kijal', stateId: 14 },
  { id: 23, name: 'Kuala Berang', stateId: 14 },
  { id: 23, name: 'Kuala Besut', stateId: 14 },
  { id: 23, name: 'Kuala Terengganu', stateId: 14 },
  { id: 23, name: 'Marang', stateId: 14 },
  { id: 23, name: 'Paka', stateId: 14 },
  { id: 23, name: 'Permaisuri', stateId: 14 },
  { id: 23, name: 'Sungai Tong', stateId: 14 },
];

const businessCategory: BusinessCategory[] = [
  { name: 'Malaysian' },
  { name: 'Chinese' },
  { name: 'Indian' },
  { name: 'Indonesian' },
  { name: 'Italian' },
  { name: 'Japanese' },
  { name: 'Korean' },
  { name: 'Mexican' },
  { name: 'Middle Eastern' },
  { name: 'Thai' },
  { name: 'Vietnamese' },
  { name: 'Asian' },
  { name: 'Western' },
  { name: 'Dessert' },
  { name: 'Coffee & Tea' },
  { name: 'Snacks' },
  { name: 'Fast Food' },
  { name: 'Cafe' },
  { name: 'Bakery' },
  { name: 'Healthy' },
  { name: 'Durian' },
];

@Injectable({
  providedIn: 'root',
})
export class DataService {
  constructor() {}

  fetchBusinessType() {
    return businessType;
  }

  fetchStates() {
    return states;
  }

  fetchCities(stateId: any) {
    return cities.filter((cities) => cities.stateId === stateId);
  }

  fetchBusinessCategory() {
    return businessCategory;
  }
}
